name: Build .NET MAUI Android app - walkabout

trigger:
- master

stages:
- stage: Build
  jobs:
    - job: Build_Android
      pool:
        vmImage: 'windows-latest'
      steps:
      - checkout: self
    
      - task: UseDotNet@2
        displayName: 'Install .NET SDK'
        inputs:
          packageType: 'sdk'
          version: '9.x'
          installationPath: '$(Agent.ToolsDirectory)/dotnet'
  
      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          restoreSolution: '**/*.sln'
  
      - script: |
          "$(Agent.ToolsDirectory)/dotnet/dotnet" workload restore
        displayName: 'Restore .NET workload dependencies'
  
      - task: android-manifest-version@1
        inputs:
          sourcePath: './AndroidManifest.xml'
          versionCodeOption: 'timestamp'
          printFile: true
  
      - script: |
          "$(Agent.ToolsDirectory)/dotnet/dotnet" build '**/hajk.csproj' `
            -c Release `
            -f net9.0-android `
            -property:AndroidSdkBuildToolsVersion=35.0.0
        displayName: 'Build .NET 9 Android'
  
      - script: |
          "$(Agent.ToolsDirectory)/dotnet/dotnet" publish '**/hajk.csproj' `
            -c Release `
            -f net9.0-android `
            -o $(Build.ArtifactStagingDirectory)/android
        displayName: 'Publish Android APK/AAB'

      - task: DownloadSecureFile@1
        displayName: 'Download keystore'
        name: downloadKeystore
        inputs:
          secureFile: 'hajk.keystore'
     
      - task: AndroidSigning@3
        displayName: 'Sign APK'
        inputs:
          apkFiles: '$(Build.ArtifactStagingDirectory)/android/*.apk'
          apksignerKeystoreFile: '$(downloadKeystore.secureFilePath)'
          apksignerKeystorePassword: '$(Keystore_Password)'
          apksignerKeystoreAlias: 'Kala'
          apksignerKeyPassword: '$(Keystore_Password)'
  
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Android artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/android'
          ArtifactName: 'android'
          publishLocation: 'Container'
