name: Build  .NET MAUI Android app

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  dotnet_version: '9.0'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: android-manifest-version@1
  inputs:
    sourcePath: './AndroidManifest.xml'
    versionCodeOption: 'timestamp'
    printFile: true

- task: UseDotNet@2
  displayName: 'Install .NET sdk'
  inputs:
    packageType: sdk
    version: '9.x'
    installationPath: '$(Agent.ToolsDirectory)/dotnet'
    
- task: CmdLine@2
  displayName: 'Install Maui Workload'
  inputs:
    script: 'dotnet workload install maui-android'

#- task: XamarinAndroid@1
#  inputs:
#    projectFile: '**/hajk.csproj'
#    outputDirectory: '$(outputDirectory)'
#    configuration: '$(buildConfiguration)'
#    msbuildVersionOption: 'latest'
#    jdkOption: 'JDKVersion'
#    jdkVersionOption: '1.11'

- task: CmdLine@2
  displayName: 'Build project'
  inputs:
    script: |
      dotnet publish $(app-path-project) -f $(app-target-framework-android) -c Release /p:ApplicationId=$(app-id-android) /p:ApplicationDisplayVersion=$(MAJOR).$(MINOR).$(PATCH).$(PRE_RELEASE) /p:ApplicationVersion=$(MAJOR)$(MINOR)$(PATCH)$(PRE_RELEASE) /p:AndroidSigningKeyPass=$(key-password) /p:AndroidSigningStorePass=$(keystore-password) /p:AndroidSigningKeyStore=$(System.DefaultWorkingDirectory)\\$(keystore-filename) /p:AndroidSigningKeyAlias=$(keystore-alias) /p:AndroidKeyStore=true
    
#- task: AndroidSigning@3
#  inputs:
#      apkFiles: '$(outputDirectory)\*.apk'
#      apksignerKeystoreFile: 'hajk.keystore'
#      apksignerKeystorePassword: '$(Keystore_Password)'
#      apksignerKeystoreAlias: 'Kala'
#      apksignerKeyPassword: '$(Keystore_Password)'

- task: PublishBuildArtifacts@1
  inputs:
      pathtoPublish: '$(outputDirectory)'
